name: Node.js CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - run: yarn
      - run: yarn build
      - run: yarn test
        env:
          CI: true
